#!/bin/bash
# Quick start guide for go2_cmd_vel_bridge

echo "========================================"
echo "GO2 cmd_vel Bridge - Quick Start"
echo "========================================"
echo ""
echo "1. Build the bridge:"
echo "   cd /home/jzw/apexuni/ApexNav"
echo "   source devel/setup.bash"
echo "   catkin_make --pkg go2_cmd_vel_bridge"
echo ""
echo "2. Check network connection:"
echo "   ping 192.168.123.161"
echo ""
echo "3. Start the bridge (Terminal 1):"
echo "   source /home/jzw/apexuni/ApexNav/devel/setup.bash"
echo "   roslaunch go2_cmd_vel_bridge cmd_vel_bridge.launch network_interface:=enp2s0"
echo ""
echo "4. Test with manual cmd_vel (Terminal 2):"
echo "   source /home/jzw/apexuni/ApexNav/devel/setup.bash"
echo "   rostopic pub /cmd_vel geometry_msgs/Twist \"linear: {x: 0.2, y: 0.0, z: 0.0} angular: {x: 0.0, y: 0.0, z: 0.3}\""
echo ""
echo "5. Or run with InSiNav trajectory planner:"
echo "   - Start traj_server (if not already running)"
echo "   - Start INSiNav exploration"
echo "   - The bridge will automatically forward cmd_vel → GO2 SDK"
echo ""
echo "========================================"
echo ""
echo "Network Configuration:"
echo "  - Robot IP: 192.168.123.161"
echo "  - Network Interface: enp2s0 (or use: ip link show)"
echo "  - DDS Domain ID: 0 (default)"
echo ""
echo "Parameters can be overridden:"
echo "  roslaunch go2_cmd_vel_bridge cmd_vel_bridge.launch domain_id:=1 max_vx:=1.0"
