#!/bin/bash
# 快速启动指南

echo "==============================================="
echo "GO2 cmd_vel Bridge - 完整启动流程"
echo "==============================================="
echo ""
echo "✅ 编译状态: 成功"
echo "✅ 可执行文件: /home/jzw/apexuni/ApexNav/devel/lib/go2_cmd_vel_bridge/cmd_vel_to_go2_bridge"
echo ""
echo "==============================================="
echo "启动流程"
echo "==============================================="
echo ""
echo "📋 前置要求："
echo "  ✓ 编译完成 (已完成)"
echo "  ✓ 网口 enp2s0 正常 (已验证)"
echo "  ✓ GO2 机器人在线 (需验证)"
echo "  ✓ ROS master 运行中 (需启动)"
echo ""
echo "-------------------------------------------"
echo "方式 1: 使用 Launch 文件（推荐）"
echo "-------------------------------------------"
echo ""
echo "# 终端1: 启动 ROS master"
echo "roscore"
echo ""
echo "# 终端2: 启动 go2_cmd_vel_bridge"
echo "source /home/jzw/apexuni/ApexNav/devel/setup.bash"
echo "roslaunch go2_cmd_vel_bridge cmd_vel_bridge.launch \\"
echo "  network_interface:=enp2s0 \\"
echo "  domain_id:=0 \\"
echo "  auto_stand:=true"
echo ""
echo "# 参数说明"
echo "  - network_interface: 网口名 (enp2s0)"
echo "  - domain_id: DDS 域ID (0 或 1)"
echo "  - auto_stand: 启动时自动站起 (true/false)"
echo "  - max_vx: 最大前进速度 (默认0.6 m/s)"
echo "  - max_vy: 最大侧向速度 (默认0.4 m/s)"
echo "  - max_yaw: 最大旋转速度 (默认1.2 rad/s)"
echo "  - cmd_timeout: 命令超时 (默认0.5 s)"
echo "  - publish_rate: 控制频率 (默认50 Hz)"
echo ""
echo "-------------------------------------------"
echo "方式 2: 直接运行可执行文件"
echo "-------------------------------------------"
echo ""
echo "# 终端1: 启动 ROS master"
echo "roscore"
echo ""
echo "# 终端2: 直接运行"
echo "source /home/jzw/apexuni/ApexNav/devel/setup.bash"
echo "rosrun go2_cmd_vel_bridge cmd_vel_to_go2_bridge \\"
echo "  _network_interface:=enp2s0 \\"
echo "  _domain_id:=0 \\"
echo "  _auto_stand:=true"
echo ""
echo "-------------------------------------------"
echo "测试桥接器"
echo "-------------------------------------------"
echo ""
echo "# 终端3: 检查节点状态"
echo "rosnode list"
echo "rosnode info /go2_cmd_vel_bridge"
echo ""
echo "# 终端3: 检查话题"
echo "rostopic list"
echo "rostopic echo /cmd_vel"
echo ""
echo "# 终端3: 发送测试命令"
echo "rostopic pub /cmd_vel geometry_msgs/Twist \\"
echo "  'linear: {x: 0.2, y: 0.0, z: 0.0} angular: {x: 0.0, y: 0.0, z: 0.3}'"
echo ""
echo "-------------------------------------------"
echo "与 INSiNav 完整集成"
echo "-------------------------------------------"
echo ""
echo "# 终端1: ROS master"
echo "roscore"
echo ""
echo "# 终端2: 启动探索系统"
echo "source /home/jzw/apexuni/ApexNav/devel/setup.bash"
echo "roslaunch exploration_manager exploration_traj.launch"
echo ""
echo "# 终端3: 启动轨迹执行"
echo "source /home/jzw/apexuni/ApexNav/devel/setup.bash"
echo "roslaunch trajectory_manager traj_server.launch"
echo ""
echo "# 终端4: 启动 INSiNav 检测"
echo "source /home/jzw/apexuni/ApexNav/devel/setup.bash"
echo "python real_world_test_example/real_world_test_insinav.py"
echo ""
echo "# 终端5: 启动 GO2 桥接器"
echo "source /home/jzw/apexuni/ApexNav/devel/setup.bash"
echo "roslaunch go2_cmd_vel_bridge cmd_vel_bridge.launch"
echo ""
echo "# 终端6: RViz 中触发探索"
echo "rviz"
echo "# 在 RViz 中点击 '2D Nav Goal' 设置目标"
echo ""
echo "-------------------------------------------"
echo "故障排查"
echo "-------------------------------------------"
echo ""
echo "问题1: 节点启动失败，说 'network_interface param is empty'"
echo "解决: 检查 launch 文件中的 network_interface 参数是否正确设置"
echo ""
echo "问题2: 无法连接 GO2"
echo "解决1: 检查网口"
echo "  ip link show | grep enp2s0"
echo "解决2: 检查 IP 连接"
echo "  ping 192.168.123.161"
echo "解决3: 检查 GO2 电源是否开启"
echo ""
echo "问题3: 机器人不动"
echo "解决1: 检查 cmd_vel 是否发布"
echo "  rostopic echo /cmd_vel"
echo "解决2: 查看桥接器日志"
echo "  roslaunch ... --ros-args --log-level DEBUG"
echo ""
echo "==============================================="
echo ""
